### ISSUE TITLE
Installation issue in OpenFOAM-v2006

### ISSUE THREAD

**Issue by delaquarme** [phorgue/porousMultiphaseFoam#23]
![image](https://user-images.githubusercontent.com/39449122/148714375-9ec04291-8d72-43ab-bfe7-66525f27f20b.png)
This is the error I got while installing it both on the ubuntu native variant and the WSL variant.

**Comment by phorgue** [comment]
It seems that your files are corrupted and the compiler cannot follow the symbolic link for the compilation of anisoImpesFoam. In the toolbox, for anisoImpesFoam for example, you have the sym-link : 

`readEvent.H -> ../impesFoam/readEvent.H`

to re-use the readEvent.H file from impesFoam solver (to avoid file duplication). Instead of symlink, you have a **readEvent.H** file containing the line 

`../impesFoam/readEvent.H`

You have to fix the symlink or restore the original folder.

Regards, 

Pierre

**Comment by k2cheffy** [comment]
Dear Pierre,
I am also having this issue. Restoring the original folder does not seem to be working and I am unsure of how to fix the symlink.
Apologies because I am very much a novice at C++.
Would it be possible for further explaination on how one would fix a symlink.

I am planning on integrating your toolbox into my dissertation project.

Thank you kindly, 
Kieran

**Update - I am using a very crude fix by duplicating the files; storage is not an issue.

**Comment by phorgue** [comment]
If your simlinks do not work, you can copy directly the files to the folder. For example, anisoImpesFoam solver re-uses 5 files from impesFoam (CourantNo.H SEqn.H computeSourceTerm.H eventWrite.H and readEvent.H). Copy these files from the folder impesFoam to the folder anisoImpesFoam and the compilation should work properly. 

However, it is better to have symlink (to avoid difference between solvers and make direct git-update working), you can find many linux tutorials on the web. 

Regards,

Pierre

**Comment by k2cheffy** [comment]
Thank you for the help, Pierre - it is greatly appreciated.
I just have one more question. How/where would I input endpoint relative permeabilities into the case for use with the impesFoam solver? Is it through the transportProperties object and if so which entries?

I am assuming residual saturations are controlled through use of Sb_max.

Sorry to be asking for this much advice. I am very thankful and you have already been included in my acknowlegements. 

Regards,
Kieran
