### ISSUE TITLE
About viscous-fingering case

### ISSUE THREAD

**Issue by tiandixuanhuang1** [phorgue/porousMultiphaseFoam#36]
Hello professor:
      I am very interested in solving the viscous fingering calculation example with impesFoam solver in your article, but I have tried for a long time without getting the desired result (sometimes errors are reported). May I take the liberty of asking if you can provide this calculation example? If you can provide this will be a great help to me!

  Best wishes : )

**Comment by phorgue** [comment]
I think that you can easily reproduce the _viscous fingering test case_ from the CPC paper starting from the _1D injection_ tutorial in  the toolbox. BC and initial conditions are similar, you should only switch to 2D dimensional domain (instead of 1D) and initialize an heterogeneous permeability field. 

For that purpose, you should use **setFields** with the **K** file in the folder **0/** (because **setFields** cannot modify file from the **constant/** folder). Then, move the permeability **K** file in **constant/** and the simulation should work.

Regards,
